(cl:in-package snake_demo-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          ENC_ANGLE1-VAL
          ENC_ANGLE1
          ENC_ANGLE2-VAL
          ENC_ANGLE2
          ENC_ANGLE3-VAL
          ENC_ANGLE3
          ENC_ANGLE4-VAL
          ENC_ANGLE4
          ENC_ANGLE5-VAL
          ENC_ANGLE5
          DXL_ANGLE1-VAL
          DXL_ANGLE1
          DXL_ANGLE2-VAL
          DXL_ANGLE2
          DXL_ANGLE3-VAL
          DXL_ANGLE3
          DXL_ANGLE4-VAL
          DXL_ANGLE4
          DXL_ANGLE5-VAL
          DXL_ANGLE5
          CMD_ANGLE1-VAL
          CMD_ANGLE1
          CMD_ANGLE2-VAL
          CMD_ANGLE2
          CMD_ANGLE3-VAL
          CMD_ANGLE3
          CMD_ANGLE4-VAL
          CMD_ANGLE4
          CMD_ANGLE5-VAL
          CMD_ANGLE5
          XVEL1-VAL
          XVEL1
          YVEL1-VAL
          YVEL1
          XVEL2-VAL
          XVEL2
          YVEL2-VAL
          YVEL2
          XVEL3-VAL
          XVEL3
          YVEL3-VAL
          YVEL3
          XVEL4-VAL
          XVEL4
          YVEL4-VAL
          YVEL4
          XVEL5-VAL
          XVEL5
          YVEL5-VAL
          YVEL5
))