(cl:in-package snake_demo-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TORQUE1-VAL
          TORQUE1
          TORQUE2-VAL
          TORQUE2
          TORQUE3-VAL
          TORQUE3
          TORQUE4-VAL
          TORQUE4
          TORQUE5-VAL
          TORQUE5
          ANGVEL1-VAL
          ANGVEL1
          ANGVEL2-VAL
          ANGVEL2
          ANGVEL3-VAL
          ANGVEL3
          ANGVEL4-VAL
          ANGVEL4
          ANGVEL5-VAL
          ANGVEL5
          ENC_ANGLE1-VAL
          ENC_ANGLE1
          ENC_ANGLE2-VAL
          ENC_ANGLE2
          ENC_ANGLE3-VAL
          ENC_ANGLE3
          ENC_ANGLE4-VAL
          ENC_ANGLE4
          ENC_ANGLE5-VAL
          ENC_ANGLE5
))