# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from snake_demo/calculations.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class calculations(genpy.Message):
  _md5sum = "0391199eca786947ffc0b714f855b349"
  _type = "snake_demo/calculations"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp
float32 torque1
float32 torque2
float32 torque3
float32 torque4
float32 torque5
float32 angvel1
float32 angvel2
float32 angvel3
float32 angvel4
float32 angvel5
float32 enc_angle1
float32 enc_angle2
float32 enc_angle3
float32 enc_angle4
float32 enc_angle5
"""
  __slots__ = ['timestamp','torque1','torque2','torque3','torque4','torque5','angvel1','angvel2','angvel3','angvel4','angvel5','enc_angle1','enc_angle2','enc_angle3','enc_angle4','enc_angle5']
  _slot_types = ['uint64','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,torque1,torque2,torque3,torque4,torque5,angvel1,angvel2,angvel3,angvel4,angvel5,enc_angle1,enc_angle2,enc_angle3,enc_angle4,enc_angle5

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(calculations, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.torque1 is None:
        self.torque1 = 0.
      if self.torque2 is None:
        self.torque2 = 0.
      if self.torque3 is None:
        self.torque3 = 0.
      if self.torque4 is None:
        self.torque4 = 0.
      if self.torque5 is None:
        self.torque5 = 0.
      if self.angvel1 is None:
        self.angvel1 = 0.
      if self.angvel2 is None:
        self.angvel2 = 0.
      if self.angvel3 is None:
        self.angvel3 = 0.
      if self.angvel4 is None:
        self.angvel4 = 0.
      if self.angvel5 is None:
        self.angvel5 = 0.
      if self.enc_angle1 is None:
        self.enc_angle1 = 0.
      if self.enc_angle2 is None:
        self.enc_angle2 = 0.
      if self.enc_angle3 is None:
        self.enc_angle3 = 0.
      if self.enc_angle4 is None:
        self.enc_angle4 = 0.
      if self.enc_angle5 is None:
        self.enc_angle5 = 0.
    else:
      self.timestamp = 0
      self.torque1 = 0.
      self.torque2 = 0.
      self.torque3 = 0.
      self.torque4 = 0.
      self.torque5 = 0.
      self.angvel1 = 0.
      self.angvel2 = 0.
      self.angvel3 = 0.
      self.angvel4 = 0.
      self.angvel5 = 0.
      self.enc_angle1 = 0.
      self.enc_angle2 = 0.
      self.enc_angle3 = 0.
      self.enc_angle4 = 0.
      self.enc_angle5 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Q15f().pack(_x.timestamp, _x.torque1, _x.torque2, _x.torque3, _x.torque4, _x.torque5, _x.angvel1, _x.angvel2, _x.angvel3, _x.angvel4, _x.angvel5, _x.enc_angle1, _x.enc_angle2, _x.enc_angle3, _x.enc_angle4, _x.enc_angle5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 68
      (_x.timestamp, _x.torque1, _x.torque2, _x.torque3, _x.torque4, _x.torque5, _x.angvel1, _x.angvel2, _x.angvel3, _x.angvel4, _x.angvel5, _x.enc_angle1, _x.enc_angle2, _x.enc_angle3, _x.enc_angle4, _x.enc_angle5,) = _get_struct_Q15f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Q15f().pack(_x.timestamp, _x.torque1, _x.torque2, _x.torque3, _x.torque4, _x.torque5, _x.angvel1, _x.angvel2, _x.angvel3, _x.angvel4, _x.angvel5, _x.enc_angle1, _x.enc_angle2, _x.enc_angle3, _x.enc_angle4, _x.enc_angle5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 68
      (_x.timestamp, _x.torque1, _x.torque2, _x.torque3, _x.torque4, _x.torque5, _x.angvel1, _x.angvel2, _x.angvel3, _x.angvel4, _x.angvel5, _x.enc_angle1, _x.enc_angle2, _x.enc_angle3, _x.enc_angle4, _x.enc_angle5,) = _get_struct_Q15f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Q15f = None
def _get_struct_Q15f():
    global _struct_Q15f
    if _struct_Q15f is None:
        _struct_Q15f = struct.Struct("<Q15f")
    return _struct_Q15f
